### ISSUE TITLE
=== ERROR: DIR is not a repository ===

### ISSUE THREAD

**Issue by haider-pw** [vicenteguerra/git-deploy#12]
Hi, i am trying to set this git-deploy with shared hosting. a2hosting.

git is enabled and exec also enabled. 

it does finds the directory.

here is how i did setup my directory in config.

define("DIR", "/home/{username}/repositories/pakistanihaider.me");

"{username}" is my account username

i created the related directory as well. and i did checked it finds the directory.

But git pull command is not being executed..??

What am i doing wrong here??

**Comment by eugenefurs** [comment]
just add the / (slash) in the end of the path and it'll work. I had the same issue and fixed it with this.

define("DIR", "/home/{username}/repositories/pakistanihaider.me/");

**Comment by Luc45** [comment]
Looking at the code that generates this error messages, there is this:

```php
if (file_exists(DIR . ".git") && is_dir(DIR)) {
    // Do something
} else {
    // === ERROR: DIR is not a repository ===
}
```

So, make sure there's a .git file in the destination directory.

**Comment by nitrokevin** [comment]
Hi I'm getting this message, sorry if this is a silly question, but why would you need a .git file in your repository, none of my repositories have .git inside them

**Comment by nitrokevin** [comment]
I have a .git folder inside my DIR but it is still saying it isn't a repository?
