### ISSUE TITLE
Bitbucket v5.11.1 not working?

### ISSUE THREAD

**Issue by ShadowFM** [vicenteguerra/git-deploy#22]
Hi, if I try to use it at Bitbucket it says:

=== ERROR: Pushed branch does not match BRANCH ===

my row for BRANCH is:
define("BRANCH", "refs/head/master");  

and I have in the repo "master" as Branch, do you know where the failure is??

Thanks for your help!

**Comment by renehamburger** [comment]
See #23.

**Comment by JacobDB** [comment]
Closing in favor of #23
