### ISSUE TITLE
[feature request] response message body

### ISSUE THREAD

**Issue by cubakcabak** [vicenteguerra/git-deploy#27]
return git pull status message as response message body to the git server.

right now the response message body received by gitlab/github are blank.

**Comment by urbanswelt** [comment]
Hi Cubakcabak,

thats the easy part, add a "Echo" in your script and choose for testing the "$result":

Line 70 in deployer.php

`
        // ensure directory is a repository
        if (file_exists(DIR .'/'. ".git") && is_dir(DIR)) {
            try {
                // pull
                fputs($file, "*** AUTO PULL INITIATED ***" . "\n");
                chdir(DIR);
                $result = shell_exec(GIT . " pull 2>&1");

                fputs($file, $result . "\n");
				ECHO $result;    // response in Body part

`

![image](https://user-images.githubusercontent.com/2138928/54979879-9e440700-4fa4-11e9-8229-0c657edfd362.png)

Edit: personal data deleted

**Comment by JacobDB** [comment]
I like this idea, currently it just immediately responds with OK as long as a token is identified, which obviously isn't ideal. I'd like to get this to respond with appropriate errors and actually send a response body that's meaningful.

I'll try to look at this when I get some spare time.

**Comment by JacobDB** [comment]
I've got this set up, along with proper HTTP response codes. I did some testing and things seemed to be working okay, but let me know if anything's not working as it should.
