### ISSUE TITLE
SSH not allowed on some hosts

### ISSUE THREAD

**Issue by JanMisker** [vicenteguerra/git-deploy#29]
Not really an issue, more like a tip:
I tried to use git-deploy on a host but failed because SSH was not accessible for the apache/php user, so `git pull` resulted in an error: `fatal: could not spawn fork`.
I managed to get it working though, switching the remote to https, and applying `git config credential.helper store`. Note that this [stores the credentials on disk](https://git-scm.com/docs/git-credential-store), so make sure this applies to your use case.

**Comment by JacobDB** [comment]
Yeah you can use `https` as well without issue, but for private repositories, you'll need to find a way to insert credentials in to the URL. I know GitLab offers "Deploy Tokens" which effectively act as read-only, single-project accounts, but I'm not sure about GitHub or BitBucket.
