### ISSUE TITLE
`DIR` always needs to end in a forward slash, otherwise the script errors

### ISSUE THREAD

**Issue by JacobDB** [vicenteguerra/git-deploy#31]
We should probably add a check for that, as it confused me for a good 15 minutes while I was trying to figure out why it wasn't working.

**Comment by urbanswelt** [comment]
Hi JacobDB,

is it this what you mean ? Without it was not possible to work in a Windows Environment.

![image](https://user-images.githubusercontent.com/2138928/54980100-1e6a6c80-4fa5-11e9-8cb0-4146cf256036.png)

**Comment by JacobDB** [comment]
Sorry, I think I meant `DIR`, not `REMOTE_REPOSITORY`, updated the title. I think adding something like below would be a simple fix to ensure that if `DIR` doesn't end in `/` it still works.

```php
$DIR = preg_replace("/([^/])$/", "$1/", DIR);
```
