### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by LeonardoSAraujo** [vicenteguerra/git-deploy#48]
Constant problems with the path 

=== ERROR: DIR `/D:/bkp-imobtotal/importacoes/` does not exist ===

=== ERROR: Pull failed using GIT `/%ProgramFiles%/Git/git-bash.exe/` and DIR `/bkp-imobtotal/importacoes/` ===
The filename, directory name, or volume label syntax is incorrect.

already chechek and are all valid paths...

Any hints?

**Comment by ArjunKishore** [comment]
For Windows you should define git path similar to this
`define("GIT", '"C:\Program Files\Git\cmd\git.exe"');`

**Comment by LeonardoSAraujo** [comment]
solved
